name: Deployment
on:
  push:
    branches:
      - '*'
      - '!docs'
    tags:
      - '*'
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install Node v14
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run docs

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: docs
          folder: docs
